let sixLetters = [
  "abrade",
  "behalf",
  "commit",
  "enough",
  "hatred",
  "native",
  "abroad",
  "belief",
  "common",
  "ensure",
  "horror",
  "nearby",
  "absorb",
  "belong",
  "comply",
  "entail",
  "hybrid",
  "nearly",
  "accept",
  "better",
  "copper",
  "entire",
  "ignore",
  "needle",
  "access",
  "bitter",
  "cotton",
  "equity",
  "inform",
  "notice",
  "accuse",
  "blazed",
  "county",
  "expand",
  "insist",
  "obtain",
  "aching",
  "blight",
  "create",
  "expect",
  "intend",
  "office",
  "active",
  "bonnet",
  "credit",
  "expert",
  "invest",
  "offset",
  "acuity",
  "boring",
  "damage",
  "extend",
  "island",
  "orange",
  "adhere",
  "borrow",
  "danger",
  "facing",
  "kindle",
  "parcel",
  "adjust",
  "bounce",
  "decent",
  "famous",
  "latter",
  "pencil",
  "admire",
  "bounty",
  "decide",
  "feared",
  "letter",
  "petrol",
  "advice",
  "braced",
  "deemed",
  "finish",
  "likely",
  "picked",
  "advise",
  "breath",
  "defeat",
  "flight",
  "liquid",
  "pledge",
  "afford",
  "brewed",
  "degree",
  "follow",
  "listen",
  "plough",
  "afraid",
  "budget",
  "demand",
  "forbid",
  "little",
  "pocket",
  "ageism",
  "burden",
  "depend",
  "forget",
  "lonely",
  "potato",
  "amazes",
  "bureau",
  "deploy",
  "formal",
  "lounge",
  "prefer",
  "amount",
  "burrow",
  "desert",
  "former",
  "luxury",
  "prince",
  "annual",
  "butter",
  "design",
  "fought",
  "manage",
  "prison",
  "appeal",
  "bygone",
  "desire",
  "freeze",
  "market",
  "proper",
  "appear",
  "canvas",
  "detail",
  "funnel",
  "matter",
  "proven",
  "arabic",
  "cashew",
  "device",
  "galore",
  "mature",
  "pursue",
  "arrive",
  "caucus",
  "differ",
  "gather",
  "mental",
  "python",
  "ashore",
  "caught",
  "double",
  "geared",
  "middle",
  "quirky",
  "asleep",
  "chance",
  "dubbed",
  "global",
  "module",
  "recall",
  "assume",
  "change",
  "effect",
  "growth",
  "monkey",
  "recent",
  "attack",
  "charge",
  "either",
  "guilty",
  "muscle",
  "refuse",
  "battle",
  "choose",
  "enable",
  "harbor",
  "myriad",
  "regime",
  "become",
  "circle",
  "engage",
  "hardly",
  "narrow",
  "regret",
  "relate",
  "spring",
  "utmost",
  "relief",
  "square",
  "vacuum",
  "remain",
  "stable",
  "virtue",
  "remote",
  "status",
  "voyage",
  "rescue",
  "steady",
  "wander",
  "resent",
  "stream",
  "warmth",
  "retain",
  "street",
  "wealth",
  "retire",
  "strict",
  "weekly",
  "reveal",
  "strike",
  "weight",
  "rhythm",
  "struck",
  "wholly",
  "rugged",
  "submit",
  "widget",
  "scanty",
  "sudden",
  "window",
  "scared",
  "suffer",
  "winter",
  "scenic",
  "supply",
  "wiring",
  "scheme",
  "taught",
  "wonder",
  "school",
  "thread",
  "wooden",
  "settle",
  "thrive",
  "wright",
  "severe",
  "throat",
  "should",
  "thrown",
  "shrink",
  "ticket",
  "signal",
  "tiptoe",
  "silver",
  "tissue",
  "simmer",
  "tongue",
  "simple",
  "treaty",
  "slight",
  "tuning",
  "smooth",
  "tunnel",
  "sorrow",
  "unable",
  "soviet",
  "unfair",
  "sponge",
  "united",
  "spread",
  "useful",
];

let sevenLetters = [
  "account",
  "compare",
  "ensnare",
  "improve",
  "operate",
  "reflect",
  "achieve",
  "compete",
  "enzymes",
  "impulse",
  "outside",
  "relieve",
  "acquire",
  "complex",
  "evening",
  "include",
  "overall",
  "replace",
  "airline",
  "concern",
  "examine",
  "initial",
  "parking",
  "request",
  "amazing",
  "confirm",
  "excited",
  "install",
  "passage",
  "require",
  "analyst",
  "connect",
  "exhibit",
  "involve",
  "patient",
  "revenge",
  "anguish",
  "consent",
  "explain",
  "jointly",
  "paucity",
  "routine",
  "another",
  "contain",
  "explore",
  "journey",
  "payment",
  "satisfy",
  "anxious",
  "control",
  "express",
  "justify",
  "perfect",
  "savings",
  "approve",
  "correct",
  "feather",
  "kingdom",
  "perform",
  "science",
  "arrange",
  "country",
  "feature",
  "kitchen",
  "phoneme",
  "seaweed",
  "arrival",
  "courage",
  "feeling",
  "leading",
  "possess",
  "serious",
  "attempt",
  "curious",
  "fellow",
  "leather",
  "powdery",
  "servant",
  "attract",
  "current",
  "fiction",
  "leisure",
  "prepare",
  "society",
  "auction",
  "curtain",
  "foreign",
  "manager",
  "pretend",
  "somehow",
  "awkward",
  "cushion",
  "forgive",
  "massive",
  "prevent",
  "specify",
  "balance",
  "decorum",
  "forward",
  "maximum",
  "proceed",
  "station",
  "beliefs",
  "deserve",
  "freeman",
  "measure",
  "process",
  "stomach",
  "believe",
  "dessert",
  "friable",
  "mention",
  "produce",
  "strange",
  "broader",
  "destroy",
  "genuine",
  "midwife",
  "promise",
  "stretch",
  "brought",
  "develop",
  "harmony",
  "minimum",
  "propose",
  "subject",
  "capable",
  "discuss",
  "healthy",
  "mission",
  "purpose",
  "succeed",
  "careful",
  "disease",
  "hearing",
  "monthly",
  "qualify",
  "suggest",
  "certain",
  "disgust",
  "helpful",
  "neglect",
  "quality",
  "support",
  "chattel",
  "dislike",
  "highway",
  "neither",
  "quarter",
  "suppose",
  "chronic",
  "driving",
  "history",
  "nervous",
  "railway",
  "survive",
  "citizen",
  "eastern",
  "holiday",
  "network",
  "reading",
  "thought",
  "classic",
  "economy",
  "illegal",
  "nowhere",
  "realize",
  "thunder",
  "comfort",
  "embassy",
  "illness",
  "observe",
  "receipt",
  "triumph",
  "company",
  "enhance",
  "impress",
  "obvious",
  "receive",
  "trouble",
  "typical",
  "unusual ",
  "various ",
  "venture ",
  "violent ",
  "visible",
  "weather ",
  "western ",
  "whistle ",
  "willing ",
  "writing",
];

let eightLetters = [
  "accuracy",
  "deletion",
  "governor",
  "nauseous",
  "relation",
  "taxation",
  "accurate",
  "designer",
  "guidance",
  "negative",
  "reliable",
  "thorough",
  "aeration",
  "disagree",
  "hawthorn",
  "northern",
  "reliance",
  "threaten",
  "alliance",
  "disclose",
  "heraldry",
  "numerous",
  "religion",
  "triptych",
  "almighty",
  "distinct",
  "hesitate",
  "nuzzling",
  "remember",
  "trousers",
  "announce",
  "dizzying",
  "homeless",
  "official",
  "research",
  "umbrella",
  "anointed",
  "doubtful",
  "ideation",
  "opposite",
  "rigorous",
  "unlawful",
  "antihero",
  "downtown",
  "identify",
  "organize",
  "roadside",
  "unlikely",
  "appendix",
  "dramatic",
  "imperial",
  "original",
  "scenario",
  "upstairs",
  "approach",
  "dynamics",
  "increase",
  "ornament",
  "scissors",
  "valuable",
  "approval",
  "eligible",
  "indebted",
  "overcome",
  "scornful",
  "volatile",
  "argument",
  "emphasis",
  "indicate",
  "overhead",
  "scrutiny",
  "wardrobe",
  "astonish",
  "enormous",
  "industry",
  "overtake",
  "sergeant",
  "weakness",
  "baritone",
  "evacuees",
  "inherent",
  "parallel",
  "sherbert",
  "wildlife",
  "behavior",
  "exchange",
  "initiate",
  "patented",
  "shortage",
  "withdraw",
  "boundary",
  "exciting",
  "involved",
  "peaceful",
  "skillful",
  "woodland",
  "breeding",
  "external",
  "iodinate",
  "persuade",
  "southern",
  "building",
  "familiar",
  "judgement",
  "physical",
  "specific",
  "business",
  "featured",
  "judicial",
  "pleasant",
  "spectrum",
  "campaign",
  "firewall",
  "language",
  "pleasure",
  "spotless",
  "carriage",
  "foothill",
  "legation",
  "portable",
  "standard",
  "cautious",
  "foremost",
  "literary",
  "postpone",
  "stocking",
  "chemical",
  "formerly",
  "maintain",
  "powerful",
  "straight",
  "churlish",
  "frazzled",
  "marriage",
  "previous",
  "strength",
  "complain",
  "frequent",
  "material",
  "profound",
  "struggle",
  "coverage",
  "friendly",
  "maximize",
  "property",
  "suitable",
  "creative",
  "gelation",
  "measured",
  "protocol",
  "surprise",
  "cultural",
  "generate",
  "minstrel",
  "publicly",
  "swimming",
  "daughter",
  "genomics",
  "mortgage",
  "purchase",
  "syllable",
  "decision",
  "gentleman",
  "mountain",
  "reaction",
  "sympathy",
];

let nineLetters = [
  "abandoner",
  "brilliant",
  "digestion",
  "hypnotize",
  "objective",
  "spotlight",
  "according",
  "bulldozer",
  "discovery",
  "hypocrisy",
  "occupancy",
  "statement",
  "afternoon",
  "calculate",
  "eagerness",
  "hypocrite",
  "otherwise",
  "structure",
  "agreement",
  "carpenter",
  "effective",
  "insurance",
  "patronage",
  "substance",
  "alongside",
  "chapstick",
  "emphasize",
  "invention",
  "plurality",
  "symbolize",
  "amazingly",
  "character",
  "excellent",
  "jellybean",
  "potential",
  "temporary",
  "amusement",
  "colleague",
  "existence",
  "jellyfish",
  "practical",
  "translate",
  "apologize",
  "committee",
  "exquisite",
  "judgement",
  "quickness",
  "treatment",
  "apparatus",
  "condition",
  "fabricate",
  "juridical",
  "razorback",
  "vaccinate",
  "attention",
  "conscious",
  "flashback",
  "knowledge",
  "recognize",
  "victimize",
  "authority",
  "criticize",
  "fortunate",
  "laborious",
  "recollect",
  "visualize",
  "automatic",
  "dangerous",
  "glamorous",
  "necessary",
  "recommend",
  "wonderful",
  "beautiful",
  "desperate",
  "greatness",
  "negotiate",
  "spearmint",
  "worthless",
  "beginning",
  "determine",
  "highlight",
  "obedience",
  "spiritual",
];

let tenLetters = [
  "abhorrence",
  "adjudicate",
  "comprehend",
  "immaculate",
  "plantation",
  "sufficient",
  "abnegation",
  "adjustment",
  "conscience",
  "impossible",
  "prosceniun",
  "suggestion",
  "abominably",
  "afterwards",
  "depression",
  "impressive",
  "punishment",
  "suspicious",
  "aborigines",
  "aggressive",
  "discussion",
  "juxtaposed",
  "reasonable",
  "texturized",
  "abridgment",
  "anticipate",
  "distribute",
  "kickboxing",
  "regardless",
  "understand",
  "abrogation",
  "appreciate",
  "equivalent",
  "literature",
  "remarkable",
  "unfriendly",
  "absolutist",
  "authorship",
  "experience",
  "maleficent",
  "seamstress",
  "volleyball",
  "absorbency",
  "background",
  "government",
  "manipulate",
  "specialist",
  "wanderlust",
  "acceptable",
  "chimpanzee",
  "hypnotized",
  "motivation",
  "squeezable",
  "widespread",
  "additional",
  "commercial",
  "illustrate",
  "mozzarella",
  "successful",
];

let elevenLetters = [
  "advertising",
  "coincidence",
  "forgettable",
  "predominate",
  "subordinate",
  "windsurfing",
  "anachronism",
  "concordance",
  "forgiveness",
  "preposition",
  "sufficiency",
  "anniversary",
  "connotation",
  "imagination",
  "requirement",
  "supposition",
  "appropriate",
  "descriptive",
  "inspiration",
  "selfishness",
  "treacherous",
  "backpacking",
  "electricity",
  "intelligent",
  "serviceable",
  "unfortunate",
  "blasphemous",
  "environment",
  "marshmallow",
  "shortcoming",
  "unstoppable",
  "celebration",
  "fabrication",
  "personality",
  "standardize",
  "vaccination",
];

let twelveLetters = [
  "abolitionist",
  "bachelorette",
  "childishness",
  "hypocritical",
  "manufacturer",
  "sporadically",
  "absoluteness",
  "behaviorally",
  "collaterally",
  "impenetrable",
  "organization",
  "thanksgiving",
  "absorptivity",
  "biodiversity",
  "commissioner",
  "independence",
  "pennsylvania",
  "unattractive",
  "academically",
  "biomagnetism",
  "cytogenetics",
  "inflammation",
  "presumptuous",
  "unsteadiness",
  "aerodynamics",
  "bodybuilding",
  "decipherable",
  "infringement",
  "professional",
  "alliteration",
  "brinkmanship",
  "decommission",
  "intellectual",
  "recalcitrant",
  "amphitheater",
  "butterscotch",
  "eclectically",
  "intelligence",
  "relationship",
  "appreciation",
  "calligrapher",
  "etymological",
  "intimidating",
  "resurrection",
  "architecture",
  "capriciously",
  "heartrending",
  "jurisdiction",
  "significance",
];

document.addEventListener("DOMContentLoaded", () => {
  const anchorEls = document.querySelectorAll("a[href='#top']");

  sixLetters = randomizeArray(sixLetters);
  sevenLetters = randomizeArray(sevenLetters);
  eightLetters = randomizeArray(eightLetters);
  nineLetters = randomizeArray(nineLetters);
  tenLetters = randomizeArray(tenLetters);
  elevenLetters = randomizeArray(elevenLetters);
  twelveLetters = randomizeArray(twelveLetters);

  anchorEls.forEach((anchorEl) => {
    //Check the categories
    anchorEl.addEventListener("click", (evt) => {
      const selected = evt.target.textContent;
      switch (selected) {
        case "6 Letters":
          changeCategory("Category: 6 Letters");
          fillGrid(sixLetters, "sixLetters");
          break;
        case "7 Letters":
          changeCategory("Category: 7 Letters");
          fillGrid(sevenLetters, "sevenLetters");
          break;
        case "8 Letters":
          changeCategory("Category: 8 Letters");
          fillGrid(eightLetters, "eightLetters");
          break;
        case "9 Letters":
          changeCategory("Category: 9 Letters");
          fillGrid(nineLetters, "nineLetters");
          break;
        case "10 Letters":
          changeCategory("Category: 10 Letters");
          fillGrid(tenLetters, "tenLetters");
          break;
        case "11 Letters":
          changeCategory("Category: 11 Letters");
          fillGrid(elevenLetters, "elevenLetters");
          break;
        case "12 Letters":
          changeCategory("Category: 12 Letters");
          fillGrid(twelveLetters, "twelveLetters");
          break;
      }
    });
  });
});

function fillGrid(array, className) {
  const grid = cleanGrid(className);
  if (grid) {
    grid.classList.add(className);

    let cont = 1;
    array.forEach((word) => {
      const div = document.createElement("div");

      div.classList.add("cell-grid");
      div.textContent = cont;

      div.addEventListener("click", () => {
        createPopup(word);
        div.classList.add("cross");
      });

      grid.append(div);
      cont++;
    });
  }
}

function cleanGrid(className) {
  const existsGrid = document.querySelector(`.${className}`);

  if (existsGrid) {
    hideGrids(existsGrid);
    return false;
  } else {
    const div = document.querySelector(".container div");
    const el = document.createElement("div");
    el.classList.add("grid");
    div.appendChild(el);
    hideGrids(el);
    return el;
  }
}

function hideGrids(selectedGrid) {
  document.querySelectorAll(".grid").forEach((el) => {
    if (el != selectedGrid) {
      el.style.display = "none";
    } else {
      el.style.display = "flex";
    }
  });
}

function changeCategory(text) {
  document.querySelector("#heading").textContent = text;
}

function createPopup(word) {
  const modal = document.getElementById("modal");
  const modalInfo = document.querySelector(".modal__info");

  modal.classList.add("modal__show");
  modalInfo.textContent = word;

  //To hide the modal
  const btnClose = document.getElementById("btnClose");

  btnClose.addEventListener("click", (evt) => {
    evt.preventDefault();
    modal.classList.remove("modal__show");
  });
}

function randomizeArray(array) {
  return array.sort((a, b) => 0.5 - Math.random());
}
